accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
  - name: bob
    coins: ["10000token", "100000000stake"]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  #vuex:
   # path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]

genesis:
  app_state:
    gov: 
      starting_proposal_id: "1"
      deposit_params:
        min_deposit: 
          - denom: "token"
            amount: "100"
        max_deposit_period: "300s"
      voting_params:
        voting_period: "300s"
      tally_params: 
          quorum: "0.334000000000000000"
          threshold: "0.500000000000000000"
          veto_threshold: "0.334000000000000000"
    