// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: policy/types.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// AccessType permission types
type AccessType int32

const (
	// AccessTypeUnspecified placeholder for empty value
	AccessTypeUnspecified AccessType = 0
	// AccessTypeNobody forbidden
	AccessTypeNobody AccessType = 1
	// AccessTypeOnlyAddress restricted to an address
	AccessTypeOnlyAddress AccessType = 2
	// AccessTypeEverybody unrestricted
	AccessTypeEverybody AccessType = 3
)

var AccessType_name = map[int32]string{
	0: "ACCESS_TYPE_UNSPECIFIED",
	1: "ACCESS_TYPE_NOBODY",
	2: "ACCESS_TYPE_ONLY_ADDRESS",
	3: "ACCESS_TYPE_EVERYBODY",
}

var AccessType_value = map[string]int32{
	"ACCESS_TYPE_UNSPECIFIED":  0,
	"ACCESS_TYPE_NOBODY":       1,
	"ACCESS_TYPE_ONLY_ADDRESS": 2,
	"ACCESS_TYPE_EVERYBODY":    3,
}

func (AccessType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_86cb898d66c46951, []int{0}
}

// RegoInfo is data for the uploaded policy REGO code
type RegoInfo struct {
	// RegoHash is the unique identifier
	RegoHash []byte `protobuf:"bytes,1,opt,name=rego_hash,json=regoHash,proto3" json:"rego_hash,omitempty"`
	// Creator address who initially stored the code
	Creator string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	// Source is a valid absolute HTTPS URI to the policy's source code,
	// optional
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// Valid entry points when using the Rego code
	EntryPoints []string `protobuf:"bytes,4,rep,name=entryPoints,proto3" json:"entryPoints,omitempty"`
	// InstantiateConfig access control to apply on policy creation, optional
	InstantiateConfig AccessConfig `protobuf:"bytes,5,opt,name=instantiate_config,json=instantiateConfig,proto3" json:"instantiate_config"`
}

func (m *RegoInfo) Reset()         { *m = RegoInfo{} }
func (m *RegoInfo) String() string { return proto.CompactTextString(m) }
func (*RegoInfo) ProtoMessage()    {}
func (*RegoInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_86cb898d66c46951, []int{0}
}
func (m *RegoInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegoInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegoInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegoInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegoInfo.Merge(m, src)
}
func (m *RegoInfo) XXX_Size() int {
	return m.Size()
}
func (m *RegoInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RegoInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RegoInfo proto.InternalMessageInfo

// AccessConfig access control type.
type AccessConfig struct {
	Permission AccessType `protobuf:"varint,1,opt,name=permission,proto3,enum=StylusFrost.policy.policy.AccessType" json:"permission,omitempty" yaml:"permission"`
	Address    string     `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty" yaml:"address"`
}

func (m *AccessConfig) Reset()         { *m = AccessConfig{} }
func (m *AccessConfig) String() string { return proto.CompactTextString(m) }
func (*AccessConfig) ProtoMessage()    {}
func (*AccessConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_86cb898d66c46951, []int{1}
}
func (m *AccessConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccessConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccessConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccessConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessConfig.Merge(m, src)
}
func (m *AccessConfig) XXX_Size() int {
	return m.Size()
}
func (m *AccessConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AccessConfig proto.InternalMessageInfo

// Params defines the set of policy parameters.
type Params struct {
	RegoUploadAccess             AccessConfig `protobuf:"bytes,1,opt,name=rego_upload_access,json=regoUploadAccess,proto3" json:"rego_upload_access" yaml:"rego_upload_access"`
	InstantiateDefaultPermission AccessType   `protobuf:"varint,2,opt,name=instantiate_default_permission,json=instantiateDefaultPermission,proto3,enum=StylusFrost.policy.policy.AccessType" json:"instantiate_default_permission,omitempty" yaml:"instantiate_default_permission"`
	MaxRegoCodeSize              uint64       `protobuf:"varint,3,opt,name=max_rego_code_size,json=maxRegoCodeSize,proto3" json:"max_rego_code_size,omitempty" yaml:"max_rego_code_size"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_86cb898d66c46951, []int{2}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("StylusFrost.policy.policy.AccessType", AccessType_name, AccessType_value)
	proto.RegisterType((*RegoInfo)(nil), "StylusFrost.policy.policy.RegoInfo")
	proto.RegisterType((*AccessConfig)(nil), "StylusFrost.policy.policy.AccessConfig")
	proto.RegisterType((*Params)(nil), "StylusFrost.policy.policy.Params")
}

func init() { proto.RegisterFile("policy/types.proto", fileDescriptor_86cb898d66c46951) }

var fileDescriptor_86cb898d66c46951 = []byte{
	// 650 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6a, 0xdb, 0x4c,
	0x14, 0xd5, 0x38, 0xfe, 0xf2, 0x33, 0x09, 0xf9, 0x9c, 0x69, 0xd2, 0x28, 0x6e, 0x2b, 0xab, 0x82,
	0x50, 0xb7, 0x04, 0x1b, 0x52, 0x68, 0x21, 0x3b, 0xff, 0x28, 0x34, 0xa5, 0xd8, 0x46, 0x4a, 0x0a,
	0x2e, 0x01, 0x31, 0x91, 0xc6, 0xb6, 0xc0, 0xd6, 0x08, 0x8d, 0x5c, 0xac, 0x3c, 0x41, 0xc9, 0xaa,
	0xab, 0xd2, 0x4d, 0x20, 0xd0, 0x2e, 0xf2, 0x28, 0x59, 0x66, 0xd9, 0x6e, 0x4c, 0xeb, 0xac, 0xba,
	0xe8, 0xc6, 0x4f, 0x50, 0x3c, 0x72, 0xd0, 0xd0, 0xd0, 0x96, 0xac, 0xa4, 0xb9, 0xf7, 0x9c, 0x7b,
	0xe6, 0x9e, 0xb9, 0x5c, 0x88, 0x7c, 0xda, 0x75, 0xed, 0xa8, 0x18, 0x46, 0x3e, 0x61, 0x05, 0x3f,
	0xa0, 0x21, 0x45, 0x1b, 0x66, 0x18, 0x75, 0xfb, 0x6c, 0x37, 0xa0, 0x2c, 0x2c, 0xc4, 0xf9, 0xe9,
	0x27, 0xbb, 0xda, 0xa6, 0x6d, 0xca, 0x51, 0xc5, 0xc9, 0x5f, 0x4c, 0xd0, 0xbe, 0x02, 0x38, 0x6f,
	0x90, 0x36, 0xdd, 0xf3, 0x5a, 0x14, 0xdd, 0x83, 0x0b, 0x01, 0x69, 0x53, 0xab, 0x83, 0x59, 0x47,
	0x06, 0x2a, 0xc8, 0x2f, 0x19, 0xf3, 0x93, 0xc0, 0x0b, 0xcc, 0x3a, 0x48, 0x86, 0x73, 0x76, 0x40,
	0x70, 0x48, 0x03, 0x39, 0xa5, 0x82, 0xfc, 0x82, 0x71, 0x7d, 0x44, 0x77, 0xe1, 0x2c, 0xa3, 0xfd,
	0xc0, 0x26, 0xf2, 0x0c, 0x4f, 0x4c, 0x4f, 0x48, 0x85, 0x8b, 0xc4, 0x0b, 0x83, 0xa8, 0x41, 0x5d,
	0x2f, 0x64, 0x72, 0x5a, 0x9d, 0xc9, 0x2f, 0x18, 0x62, 0x08, 0x1d, 0x42, 0xe4, 0x7a, 0x2c, 0xc4,
	0x5e, 0xe8, 0xe2, 0x90, 0x58, 0x36, 0xf5, 0x5a, 0x6e, 0x5b, 0xfe, 0x4f, 0x05, 0xf9, 0xc5, 0xed,
	0x47, 0x85, 0x3f, 0xf6, 0x52, 0x28, 0xd9, 0x36, 0x61, 0xac, 0xc2, 0xe1, 0xe5, 0xf4, 0xc5, 0x30,
	0x27, 0x19, 0x2b, 0x42, 0xa1, 0x38, 0xa1, 0x9d, 0x01, 0xb8, 0x24, 0x22, 0xd1, 0x21, 0x84, 0x3e,
	0x09, 0x7a, 0x2e, 0x63, 0x2e, 0xf5, 0x78, 0x83, 0xcb, 0xdb, 0x9b, 0xff, 0x94, 0xd9, 0x8f, 0x7c,
	0x52, 0x5e, 0x1b, 0x0f, 0x73, 0x2b, 0x11, 0xee, 0x75, 0x77, 0xb4, 0xa4, 0x84, 0x66, 0x08, 0xf5,
	0xd0, 0x16, 0x9c, 0xc3, 0x8e, 0x13, 0x10, 0xc6, 0x62, 0x83, 0xca, 0x68, 0x3c, 0xcc, 0x2d, 0xc7,
	0x9c, 0x69, 0x42, 0x33, 0xae, 0x21, 0x3b, 0xe9, 0x8f, 0x67, 0x39, 0xa0, 0xfd, 0x4c, 0xc1, 0xd9,
	0x06, 0x0e, 0x70, 0x8f, 0xa1, 0x01, 0x44, 0xdc, 0xfc, 0xbe, 0xdf, 0xa5, 0xd8, 0xb1, 0x30, 0xd7,
	0xe6, 0x97, 0xbc, 0x85, 0x17, 0x0f, 0x27, 0x5e, 0x8c, 0x87, 0xb9, 0x8d, 0x58, 0xf6, 0x66, 0x41,
	0xcd, 0xc8, 0x4c, 0x82, 0x07, 0x3c, 0x16, 0x53, 0xd1, 0x07, 0x00, 0x15, 0xf1, 0x19, 0x1c, 0xd2,
	0xc2, 0xfd, 0x6e, 0x68, 0x09, 0x5e, 0xa5, 0x6e, 0xe3, 0xd5, 0xe3, 0xf1, 0x30, 0xb7, 0x19, 0x5f,
	0xe0, 0xef, 0x65, 0x35, 0xe3, 0xbe, 0x00, 0xa8, 0xc6, 0xf9, 0x46, 0xe2, 0xe8, 0x4b, 0x88, 0x7a,
	0x78, 0x60, 0xf1, 0x2e, 0x6c, 0xea, 0x10, 0x8b, 0xb9, 0xc7, 0xf1, 0x90, 0xa5, 0xcb, 0x0f, 0x92,
	0x2e, 0x6f, 0x62, 0x34, 0xe3, 0xff, 0x1e, 0x1e, 0x4c, 0xe6, 0xba, 0x42, 0x1d, 0x62, 0xba, 0xc7,
	0x84, 0xfb, 0x2d, 0x3d, 0xf9, 0x01, 0x20, 0x4c, 0x6e, 0x8a, 0x9e, 0xc1, 0xf5, 0x52, 0xa5, 0xa2,
	0x9b, 0xa6, 0xb5, 0xdf, 0x6c, 0xe8, 0xd6, 0x41, 0xcd, 0x6c, 0xe8, 0x95, 0xbd, 0xdd, 0x3d, 0xbd,
	0x9a, 0x91, 0xb2, 0x1b, 0x27, 0xa7, 0xea, 0x5a, 0x02, 0x3e, 0xf0, 0x98, 0x4f, 0x6c, 0xb7, 0xe5,
	0x12, 0x07, 0x6d, 0x41, 0x24, 0xf2, 0x6a, 0xf5, 0x72, 0xbd, 0xda, 0xcc, 0x80, 0xec, 0xea, 0xc9,
	0xa9, 0x9a, 0x49, 0x28, 0x35, 0x7a, 0x44, 0x9d, 0x08, 0x3d, 0x87, 0xb2, 0x88, 0xae, 0xd7, 0x5e,
	0x35, 0xad, 0x52, 0xb5, 0x6a, 0xe8, 0xa6, 0x99, 0x49, 0xfd, 0x2e, 0x53, 0xf7, 0xba, 0x51, 0x29,
	0x9e, 0x11, 0xb4, 0x0d, 0xd7, 0x44, 0xa2, 0xfe, 0x5a, 0x37, 0x9a, 0x5c, 0x69, 0x26, 0xbb, 0x7e,
	0x72, 0xaa, 0xde, 0x49, 0x58, 0xfa, 0x5b, 0x12, 0x44, 0x13, 0xb1, 0xec, 0xfc, 0xbb, 0x4f, 0x8a,
	0x74, 0xfe, 0x59, 0x91, 0xca, 0xb5, 0x8b, 0xef, 0x8a, 0x74, 0x3e, 0x52, 0xc0, 0xc5, 0x48, 0x01,
	0x97, 0x23, 0x05, 0x7c, 0x1b, 0x29, 0xe0, 0xfd, 0x95, 0x22, 0x5d, 0x5e, 0x29, 0xd2, 0x97, 0x2b,
	0x45, 0x7a, 0xb3, 0xd5, 0x76, 0xc3, 0x4e, 0xff, 0xa8, 0x60, 0xd3, 0x5e, 0x51, 0x78, 0xd9, 0xe2,
	0x74, 0xb1, 0x0c, 0x8a, 0xe2, 0x86, 0x39, 0x9a, 0xe5, 0x1b, 0xe3, 0xe9, 0xaf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x72, 0xbe, 0x10, 0xcd, 0x78, 0x04, 0x00, 0x00,
}

func (this *RegoInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RegoInfo)
	if !ok {
		that2, ok := that.(RegoInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.RegoHash, that1.RegoHash) {
		return false
	}
	if this.Creator != that1.Creator {
		return false
	}
	if this.Source != that1.Source {
		return false
	}
	if len(this.EntryPoints) != len(that1.EntryPoints) {
		return false
	}
	for i := range this.EntryPoints {
		if this.EntryPoints[i] != that1.EntryPoints[i] {
			return false
		}
	}
	if !this.InstantiateConfig.Equal(&that1.InstantiateConfig) {
		return false
	}
	return true
}
func (this *AccessConfig) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AccessConfig)
	if !ok {
		that2, ok := that.(AccessConfig)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Permission != that1.Permission {
		return false
	}
	if this.Address != that1.Address {
		return false
	}
	return true
}
func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.RegoUploadAccess.Equal(&that1.RegoUploadAccess) {
		return false
	}
	if this.InstantiateDefaultPermission != that1.InstantiateDefaultPermission {
		return false
	}
	if this.MaxRegoCodeSize != that1.MaxRegoCodeSize {
		return false
	}
	return true
}
func (m *RegoInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegoInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RegoInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.InstantiateConfig.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.EntryPoints) > 0 {
		for iNdEx := len(m.EntryPoints) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.EntryPoints[iNdEx])
			copy(dAtA[i:], m.EntryPoints[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.EntryPoints[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Source) > 0 {
		i -= len(m.Source)
		copy(dAtA[i:], m.Source)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Source)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RegoHash) > 0 {
		i -= len(m.RegoHash)
		copy(dAtA[i:], m.RegoHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.RegoHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AccessConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccessConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccessConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if m.Permission != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Permission))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxRegoCodeSize != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MaxRegoCodeSize))
		i--
		dAtA[i] = 0x18
	}
	if m.InstantiateDefaultPermission != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.InstantiateDefaultPermission))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.RegoUploadAccess.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RegoInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RegoHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Source)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.EntryPoints) > 0 {
		for _, s := range m.EntryPoints {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	l = m.InstantiateConfig.Size()
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func (m *AccessConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Permission != 0 {
		n += 1 + sovTypes(uint64(m.Permission))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.RegoUploadAccess.Size()
	n += 1 + l + sovTypes(uint64(l))
	if m.InstantiateDefaultPermission != 0 {
		n += 1 + sovTypes(uint64(m.InstantiateDefaultPermission))
	}
	if m.MaxRegoCodeSize != 0 {
		n += 1 + sovTypes(uint64(m.MaxRegoCodeSize))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RegoInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegoInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegoInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegoHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegoHash = append(m.RegoHash[:0], dAtA[iNdEx:postIndex]...)
			if m.RegoHash == nil {
				m.RegoHash = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Source = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EntryPoints", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EntryPoints = append(m.EntryPoints, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InstantiateConfig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InstantiateConfig.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccessConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccessConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccessConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Permission", wireType)
			}
			m.Permission = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Permission |= AccessType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegoUploadAccess", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RegoUploadAccess.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InstantiateDefaultPermission", wireType)
			}
			m.InstantiateDefaultPermission = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InstantiateDefaultPermission |= AccessType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxRegoCodeSize", wireType)
			}
			m.MaxRegoCodeSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxRegoCodeSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
